FROM node:18.17.1-alpine3.18

# set working directory
WORKDIR /app

# install deps
COPY package.json package-lock.json* ./
RUN npm install --production

# copy backend source
COPY . .

EXPOSE 3000
CMD ["node", "server.js"]